### ISSUE TITLE
The Photo Scrolling has some Issues

### ISSUE THREAD

**Issue by nirabpudasaini** [MeghaStha/khetibali#2]
![khetibali_issue_with_picturescrool](https://cloud.githubusercontent.com/assets/3871904/8104693/5f3f02d4-1052-11e5-89ea-17cec7a732dd.png)
The picture only half scrolls at time and is stuck in this position.

**Comment by MeghaStha** [comment]
It should not be the case. I tested it in mine and it works just fine. Btw the picture scrolls equal to the amount of mouse scroll.

**Comment by MeghaStha** [comment]
Done...
