### ISSUE TITLE
The Navigation Sidebar Misbehaviour

### ISSUE THREAD

**Issue by nirabpudasaini** [MeghaStha/khetibali#3]
When you go to either "The Mapping Process" and "About Khetibali" menu you can now expand all three VDC at the same time, Also their CSS is different. 

![khetibali_issue_sidebar](https://cloud.githubusercontent.com/assets/3871904/8104857/f623dac0-1053-11e5-82b0-8ede20948c43.png)

![khetibali_issue_sidebar1](https://cloud.githubusercontent.com/assets/3871904/8104868/045b29ae-1054-11e5-8f7b-9e4e1bceb877.png)

If this is intended behavior it is a bit unintutive and also since scrolling is not available in the sidebar some items get hidden.

**Comment by MeghaStha** [comment]
Now you cannot expand it. When you click on the VDC map appears
